### ISSUE TITLE
Use mistral as planner

### ISSUE THREAD

**Issue by lingchensanwen** [OSU-NLP-Group/TravelPlanner#24]
Hi team,

Thank you for the great work. I tried to replicate the part for using mistral as planner and I noticed that in [tool_agent.py](https://github.com/OSU-NLP-Group/TravelPlanner/blob/main/agents/tool_agents.py) and [api.py](https://github.com/OSU-NLP-Group/TravelPlanner/blob/main/tools/planner/apis.py) The part of mistral is always loading gpt3.5 instead. I'm wondering if you did this on purpose? I tried to replace both for mistral
for example

```
if model_name in ['mistral']:
            self.max_token_length = 30000
            self.llm = ChatOpenAI(temperature=0,
                     max_tokens=4096,
                     openai_api_key="token-abc123", 
                     openai_api_base="http://localhost:8000/v1", 
                     model_name="mistralai/Mistral-7B-Instruct-v0.3")
```

However the following process steps fail - parsing is fine but then it shows the output is not in json as sometime mistral_two-stage_results is "".

Did you meet it before? How did you solve this issue in your mistral planning part? Looking forward to hearing from you.

**Comment by hsaest** [comment]
Hi Yating,

Thanks for your interest in our work.

We actually do this on purpose, please refer to [this](https://github.com/OSU-NLP-Group/TravelPlanner/issues/14#issuecomment-2011082035).

I cannot assess what happened since I don’t see the detailed responses from the planner. However, if I remember correctly, Mistral cannot always deliver a plan, so you might want to check Mistral’s outputs.

Best,
Jian

**Comment by lingchensanwen** [comment]
thank you Jian! I'll check what's wrong on the mistral side.
