### ISSUE TITLE
direct output for json format plan 

### ISSUE THREAD

**Issue by yananchen1989** [OSU-NLP-Group/TravelPlanner#30]
hi author. 

have u ever considered making the planner llm to directly out the plan which can be json parsable. which means that using eval to parse it, rather than sending it to gpt to for json conversion. 

if not, may i know the reason ?  is few shots demonstration not good enough to make it ? 

as u know, requesting gpt for this json conversion costs money and time. and make the pipeline not that smooth. 

looking forward your opinions. 

thanks

**Comment by hsaest** [comment]
Hi Yanan,

It’s fine to directly output the plan in JSON format as long as the model can produce it in standard JSON. We include this additional step because, at the time of our project’s development, GPT-4 did not consistently support JSON output (but support now) in the long context, and other open-source models also struggled to provide consistently parsable JSON.

We strongly encourage and are pleased to see follow-up work aimed at simplifying the process of obtaining results. If you are interested in contributing to this effort, we would greatly appreciate your PR.

Best,
Jian

**Comment by yananchen1989** [comment]
make sense. thanks.

**Comment by hsaest** [comment]
Hi Yanan,

Thank you sincerely for your valuable contribution! I will be adding this feature soon, and you are welcome to submit a pull request directly if you wish.

Best,
Jian

**Comment by Luyunfei0728** [comment]
> 嗨，作者。
> 
> 你有没有考虑过让规划师 LLM 直接出可以 JSON 解析的计划。这意味着使用 eval 来解析它，而不是将其发送到 GPT 进行 JSON 转换。
> 
> 如果没有，我可以知道原因吗？是不是 Few Shots 演示还不够好？
> 
> 如您所知，为此 JSON 转换请求 GPT 需要花费金钱和时间。并使管道不那么顺畅。
> 
> 期待您的意见。
> 
> 谢谢

我也遇到了这个问题，在调用模型转化格式的时候有部分结果是转不成要求的格式的，是不是可以直接写个脚本来转换啊？速度快也省钱

**Comment by hsaest** [comment]
Hi,

In my previous test, it was hard to enumerate all exceptions. 

The best solution may be to require LLMs to output plans in JSON format. Unfortunately, I am too busy these days to provide a new version. Please follow Yanan's code.

**Comment by Luyunfei0728** [comment]
Hi
When the model generates a response, it sometimes ignores the day limit and produces plans longer than 7 days, which results in an incorrect JSON format.
I would like to ask how you handled this.
